---
- name: Create Linux VM in vSphere
  hosts: localhost  
  connection: local
  gather_facts: no
  vars:
    tower_user:
    tower_password:
    vm_name: rhel7-0088
   
  tasks:
    - name: Create host in inventory to pass to next playbook
      command: "tower-cli host create -n {{ vm_name }} -i 'Linux Inventory' --variables='{"ansible_user": "root", "ansible_host": "100.9.133.13"}'"