---
- name: Create Linux VM in vSphere
  hosts: localhost  
  connection: local
  gather_facts: no
  vars:
    tower_user: 
    tower_password:
    vm_name: rhel7-0088
   
  tasks:
   - name: reate host in inventory to pass to next playbook
     command: "{{ item }}"
     with_items:
       - tower-cli config host localhost
       - tower-cli login {{ tower_user }} --password {{ tower_password }}
       - tower-cli host create -n {{ vm_name }} -i 'Linux Inventory' --variables='{"ansible_user":"root", "ansible_host":"100.9.133.13"}'

   # - name: Create host in inventory to pass to next playbook
   #   shell: |
   #     tower-cli config host localhost
   #     tower-cli login {{ tower_user }} --password {{ tower_password }}
   #     tower-cli host create -n {{ vm_name }} -i 'Linux Inventory' --variables='{"ansible_user":"root", "ansible_host":"100.9.133.13"}'