- name: Known Error Demo (batch copy fail)
  hosts: all
  connection: local
  become_method: sudo
  become_user: root
  vars:
   username:
   password:
   instance:
  
  tasks:

    - name: Batch job - copy files remotely
      copy: 
        src: ~/testdir/dummy.iso
        dest: /tmp/dummy.iso
      #validate: /usr/sbin/visudo -cf %s
      register: errorCode
      changed_when:  "'Killed' in errorCode.stderr"

    - name: look at errorCode
      debug:
        var: errorCode

    - name: SERVICENOW incident created if Known Error detected
      block:
        - name: CREATE AN INCIDENT
          snow_record:
            username: "{{username}}"
            password: "{{password}}"
            instance: "{{instance}}"
            state: present
            table: incident
            data:
              short_description: "Known Error On {{inventory_hostname}} was found: Batch Job: File Copy Failed"
              severity: 1
              priority: 2
              caller_id: "System Administrator"
              comments: "The batch job copy:\n--------\n {% for item in errorCode.updates %}{{item}}\n{% endfor %}\n--------\n failed on {{inventory_hostname}}"
          register: snow_var
          delegate_to: localhost

        - name: DEBUG SNOW_VAR
          debug:
            var: snow_var.record.number
      when: errorCode.changed