- name: Known Error Demo (batch copy fail)
  hosts: all
  vars:
    username: 
    password:
    instance:
    number:
  
  tasks:
    
    - name: include vars
      include_vars: incident_vars.yaml
    
    - name: Batch job - copy files remotely
      command: cp /mnt/testdir/dummy.iso /tmp/testdir/dummy.iso
      #validate: /usr/sbin/visudo -cf %s
      register: errorCode
      ignore_errors: True
      #changed_when: errorCode.rc == 0

    - name: look at errorCode
      debug:
        var: errorCode

    - name: SERVICENOW incident udated if copy succeeded
      snow_record:
        username: "{{username}}"
        password: "{{password}}"
        instance: "{{instance}}"
        number: "{{number}}"
        state: present
        table: incident
        data:
          caller_id: "System Administrator"
          comments: "The batch job has now succeeded on {{inventory_hostname}}. This ticket was updated by Ansible Tower API call in a remediation playboook. \n--------\n The status code is {{errorCode.rc}}\n--------\n "
      register: snow_var
      delegate_to: localhost
      #when: errorCode.changed

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.state