- name: Known Error Demo (batch copy fail)
  hosts: all

  vars:
   username:
   password:
   instance:
  
  tasks:

    - name: Batch job - copy files remotely
      copy:
        src: /mnt/testdir/dummy.iso 
        dest: /tmp/testdir/dummy.iso
        remote_src: yes
      #validate: /usr/sbin/visudo -cf %s
      register: errorCode
      #ignore_errors: True
      #changed_when: False

    - name: look at errorCode
      debug:
        var: errorCode
      #changed_when: "'Killed' in errorCode.stdout"

    - name: SERVICENOW incident created if Known Error detected
      block:
        - name: CREATE AN INCIDENT
          snow_record:
            username: "{{username}}"
            password: "{{password}}"
            instance: "{{instance}}"
            state: present
            table: incident
            data:
              short_description: "Known Error On {{inventory_hostname}} was found: Batch Job: File Copy Failed"
              severity: 1
              priority: 2
              caller_id: "System Administrator"
              comments: "The batch job copy:\n--------\n {% for item in errorCode.updates %}{{item}}\n{% endfor %}\n--------\n failed on {{inventory_hostname}}"
          register: snow_var
          delegate_to: localhost

        - name: DEBUG SNOW_VAR
          debug:
            var: snow_var.record.number
      when: errorCode.changed