- name: Known Error Demo (batch copy fail)
  hosts: all
  
  tasks:

    #- name: Batch job - copy files remotely
    #  copy:
    #    src: /mnt/testdir/dummy.iso 
    #    dest: /tmp/testdir/dummy.iso
    #    remote_src: yes
    #  #validate: /usr/sbin/visudo -cf %s
    #  register: errorCode
    #  #ignore_errors: True
    #  #changed_when: False
    
    - name: Batch job - copy files remotely
      command: cp /mnt/testdir/dummy.iso /tmp/testdir/dummy.iso
      #validate: /usr/sbin/visudo -cf %s
      register: errorCode
      ignore_errors: True
      #changed_when: False
      changed_when: errorCode.rc == -9

    - name: look at errorCode
      debug:
        var: errorCode
      #changed_when: "'Killed' in errorCode.stdout"
      #changed_when: "errorCode.rc = -9"

    - name: SERVICENOW incident created if Known Error detected
      #block:
      # - name: CREATE AN INCIDENT
      #connection: local
      snow_record:
        username: admin
        password: MyPassw0rd21
        instance: dev14202
        state: present
        table: incident
        data:
          short_description: "Known Error On app host was found: Batch Job: File Copy Failed"
          severity: 1
          priority: 2
          caller_id: "System Administrator"
          comments: "The batch job copy failed on {{inventory_hostname}}. This ticket was generated by Ansible Tower API call.\n--------\n\n--------\n "
      register: snow_var
      delegate_to: localhost
      when: errorCode.changed

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.number
      #when: errorCode.changed