- name: Known Error Demo (batch copy fail)
  hosts: all
  
  tasks:
  
    - name: SERVICENOW incident created if Known Error detected
      #block:
      # - name: CREATE AN INCIDENT
      #connection: local
      snow_record:
        username: admin
        password: MyPassw0rd21
        instance: dev14202
        state: present
        table: incident
        data:
          short_description: "Known Error On app host was found: Batch Job: File Copy Failed"
          severity: 1
          priority: 2
          caller_id: "System Administrator"
          comments: "The batch job copy:\n--------\n {% for item in errorCode.updates %}{{item}}\n{% endfor %}\n--------\n failed on{inventory_hostname}}"
      register: snow_var
      delegate_to: localhost
      #when: errorCode.changed

    - name: DEBUG SNOW_VAR
      debug:
        var: snow_var.record.number