---
- name: Check for web based application health
  hosts: all


  tasks:
   - name: Check that you can connect (GET) to a page and it returns a status 200
     uri:
       url: http://54.190.212.205/
       return_content: yes
     register: app_health
     ignore_errors: True
     changed_when: False
     #failed_when: app_health.status != 200
     
   - name: "Print status"
     debug: msg=""
     changed_when: app_health.status != 200
     notify: App is not running, restart HTTPD

  handlers: 
   - name: App is not running, restart HTTPD
     service:
      name: httpd
      state: started
     #when: app_health.status != 200
